### ISSUE TITLE
Missing part of gupnp 1.6 port

### ISSUE THREAD

**Issue by DimStar77** [phako/dleyna-renderer#11]
https://github.com/phako/dleyna-renderer/blob/b3a06c8bc4b91803d7bde312f49a68109b8ad8d4/libdleyna/renderer/meson.build#L60

There is still reference to gupnp 1.2 here, despite the port to 1.6

**Comment by phako** [comment]
Thanks. Fixed here: https://gitlab.gnome.org/World/dLeyna/-/commit/db06bfa322c80256bab50896d9692bac5d9c2bef
