### ISSUE TITLE
dleyna-renderer-service is missing RPATH

### ISSUE THREAD

**Issue by heftig** [phako/dleyna-renderer#6]
The installed executable links to `libdleyna-renderer-1.0.so.1`, however, that library is in the non-standard dir `/usr/lib/dleyna-renderer/` and the executable is missing a matching rpath, thus cannot run.

This is a regression in 0.7.0.

**Comment by heftig** [comment]
https://github.com/phako/dleyna-server has a similar problem but that repository has issues deactivated.

**Comment by phako** [comment]
Yes and I forgot to enable notifications as well, sorry.
