### ISSUE TITLE
Process 97235 (dleyna-renderer) of user 1000 dumped core.

### ISSUE THREAD

**Issue by tapsiturtle** [phako/dleyna-renderer#7]
Hi,

i get an coredump all the time. At first i found the following entry in m logs:
kernel: traps: dleyna-renderer[97235] trap divide error ip:7f765baa87b8 sp:7ffe9005b6a0 error:0 in libglib-2.0.so.0.6800.2[7f765ba8e000+8c00>

After that i get an coredump, see attached file.
[dleyna-gdb.log](https://github.com/phako/dleyna-renderer/files/6583061/dleyna-gdb.log)

I'm using ArchLinux with newest packages. It seems that there are no problems with apps, i just get this coredump more than once a day.

**Comment by phako** [comment]
- Can you please check the version of dleyna-renderer
- This trace is a bit useless without debug information, sorry

**Comment by tapsiturtle** [comment]
Version is 0.7.0
I will try to get debug symbols.

**Comment by phako** [comment]
If your GUPnP version is >= 1.2.6 I think I know the problem

**Comment by tapsiturtle** [comment]
Yes, it is 1.2.6

**Comment by tapsiturtle** [comment]
New debug log:
[dleyna-gdb.log](https://github.com/phako/dleyna-renderer/files/6589995/dleyna-gdb.log)

**Comment by phako** [comment]
Thanks, yes, that what I saw in #9 and an issue in GUPnP
